apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: familie-prosessering
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  replicas:
    min: 1
    max: 1
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  ingresses:
    - "https://familie-prosessering.intern.nav.no"
  azure:
    application:
      enabled: true
      replyURLs:
        - 'https://familie-prosessering.intern.nav.no/auth/openid/callback'
      claims:
        groups:
          - id: "87190cf3-b278-457d-8ab7-1a5c55a9edd7" # teamfamilie
  accessPolicy:
    outbound:
      rules:
        - application: familie-ef-sak
        - application: familie-ef-personhendelse
        - application: familie-ef-iverksett
        - application: familie-klage
        - application: familie-ef-mottak
        - application: familie-ba-sak
        - application: familie-ks-sak
        - application: familie-ks-barnehagelister
        - application: familie-baks-mottak
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
      cpu: 20m
  envFrom:
    - secret: familie
    - secret: prosessering
  env:
    - name: ENV
      value: prod