apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: familie-prosessering
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  replicas:
    min: 1
    max: 1
  ingresses:
    - "https://familie-prosessering.intern.dev.nav.no"
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
      replyURLs:
        - 'https://familie-prosessering.intern.dev.nav.no/auth/openid/callback'
  accessPolicy:
    outbound:
      rules:
        - application: familie-ef-sak
        - application: familie-ef-iverksett
        - application: familie-tilbake
        - application: familie-klage
        - application: familie-ef-mottak
        - application: familie-ba-sak
        - application: familie-ks-sak
        - application: familie-baks-mottak
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
      cpu: 20m
  envFrom:
    - secret: familie
    - secret: prosessering
  env:
    - name: ENV
      value: dev