# Full pipeline on push to main. Build, test, and deploy to dev + prod
name: Build and deploy app to dev and prod
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.github/**.yaml'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'

jobs:
  build:
    name: Build
    if: github.ref == 'refs/heads/main' # Only deploy to prod from main branch
    permissions:
      contents: read
      id-token: write
    uses: navikt/familie-baks-gha-workflows/.github/workflows/build-pnpm-app.yaml@main # ratchet:exclude
    with:
      node-version: '24'
      build-image: true
      push-image: true
    secrets: inherit
  deploy-dev-teamfamilie:
    name: Deploy to Dev teamfamilie
    permissions:
      contents: read
      id-token: write
    needs: [build]
    uses: navikt/familie-baks-gha-workflows/.github/workflows/deploy.yaml@main # ratchet:exclude
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: dev-gcp
      resource: .nais/app-dev.yaml
    secrets: inherit
  deploy-dev-tilleggsstonader:
    name: Deploy to Dev tilleggsstonader
    permissions:
      contents: read
      id-token: write
    needs: [build]
    uses: navikt/familie-baks-gha-workflows/.github/workflows/deploy.yaml@main # ratchet:exclude
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: dev-gcp
      resource: .nais/app-dev-tilleggsstonader.yaml
    secrets: inherit
  deploy-dev-tilbakekreving:
    name: Deploy to Dev tilbakekreving
    permissions:
      contents: read
      id-token: write
    needs: [build]
    uses: navikt/familie-baks-gha-workflows/.github/workflows/deploy.yaml@main # ratchet:exclude
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: dev-gcp
      resource: .nais/app-dev-tilbake.yaml
    secrets: inherit
  deploy-dev-etterlatte:
    name: Deploy to Dev etterlatte
    permissions:
      contents: read
      id-token: write
    needs: [build]
    uses: navikt/familie-baks-gha-workflows/.github/workflows/deploy.yaml@main # ratchet:exclude
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: dev-gcp
      resource: .nais/app-dev-etterlatte.yaml
    secrets: inherit
  deploy-prod-teamfamilie:
    name: Deploy to Prod teamfamilie
    permissions:
      contents: read
      id-token: write
    needs: [build]
    uses: navikt/familie-baks-gha-workflows/.github/workflows/deploy.yaml@main # ratchet:exclude
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: prod-gcp
      resource: .nais/app-prod.yaml
    secrets: inherit
  deploy-prod-tilleggsstonader:
    name: Deploy to Prod tilleggsstonader
    permissions:
      contents: read
      id-token: write
    needs: [build]
    uses: navikt/familie-baks-gha-workflows/.github/workflows/deploy.yaml@main # ratchet:exclude
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: prod-gcp
      resource: .nais/app-prod-tilleggsstonader.yaml
    secrets: inherit
  deploy-prod-tilbakekreving:
    name: Deploy to Prod tilbakekreving
    permissions:
      contents: read
      id-token: write
    needs: [build]
    uses: navikt/familie-baks-gha-workflows/.github/workflows/deploy.yaml@main # ratchet:exclude
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: prod-gcp
      resource: .nais/app-prod-tilbake.yaml
    secrets: inherit
