name: Manual deploy to dev
on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Hvilket dev-miljø skal deployes?'
        required: true
        type: choice
        options:
          - teamfamilie
          - tilleggsstonader
          - tilbake
          - etterlatte
      skip-tests:
        description: 'Skip tests?'
        default: false
        type: boolean
      skip-validation:
        description: 'Skip validation? (typecheck, lint)'
        default: false
        type: boolean

jobs:
  build:
    name: Build
    permissions:
      contents: read
      id-token: write
    uses: navikt/familie-baks-gha-workflows/.github/workflows/build-pnpm-app.yaml@main # ratchet:exclude
    with:
      node-version: '24'
      build-image: true
      push-image: true
      skip-tests: ${{ inputs.skip-tests }}
      skip-validation: ${{ inputs.skip-validation }}
    secrets: inherit
  deploy:
    name: Deploy to dev - ${{ inputs.namespace }}
    permissions:
      contents: read
      id-token: write
    needs: [build]
    uses: navikt/familie-baks-gha-workflows/.github/workflows/deploy.yaml@main # ratchet:exclude
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: dev-gcp
      resource: ${{ inputs.namespace == 'teamfamilie' && '.nais/app-dev.yaml' || format('.nais/app-dev-{0}.yaml', inputs.namespace) }}
    secrets: inherit
